[package]
name = "pcaps"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
log = "0.4.22"
crossterm = "0.28.1"
ratatui = "0.28.0"
shark = { path = "../shark"}
# unicode-width = "0.2.0"
anyhow = "1.0.91"
tui-tree-widget = "0.22.0"
