import React from 'react';
import { createRoot } from 'react-dom/client';
import Application from './app';
import 'primeflex/primeflex.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/md-dark-indigo/theme.css';
// import 'primereact/resources/themes/mdc-light-deeppurple/theme.css';
// import 'primereact/resources/themes/viva-dark/theme.css';
// import 'primereact/resources/themes/soho-dark/theme.css';
// import 'primereact/resources/themes/lara-dark-blue/theme.css';
import './index.css';
const container = document.getElementById('app') as HTMLElement;
const root = createRoot(container);
root.render(<Application/>);