[package]
name = "pcap_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[[test]]
name = "test"
path = "test/progress.rs"

[dependencies]
syn.workspace = true
quote.workspace = true