[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
shark = { path = "../shark"}
once_cell.workspace = true


[dev-dependencies]
prettytable-rs.workspace = true
env_logger.workspace = true
