[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
shark = { path = "../shark"}
once_cell.workspace = true


[dev-dependencies]
prettytable-rs = "^0.10"
env_logger = "0.11.3"
