name: Rust

on:
  push:
    branches: [ "release/*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    steps:
    - uses: actions/checkout@v4
    - name: ENV
      run: |
        cargo --version
        rustc -vV
        echo "version ${GITHUB_REF#refs/heads/release/}"
    - run: echo "brc=$(echo ${GITHUB_REF#refs/heads/release/})" >> $GITHUB_ENV
    - name: Build
      run: cargo build --release --target ${{ matrix.target }} --verbose
    - run: mkdir release
    - run: mv target/${{ matrix.target }}/release/pcaps release/pcaps-${{ matrix.target }}
    - name: Release TUI
      uses: softprops/action-gh-release@v2.1.0
      with:
        tag_name: ${{ env.brc }}
        files: |
          release/pcaps-${{ matrix.target }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
