name: Build_web_demo

on:
  push:
    branches: [ "release/*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ENV
      run: |
        cargo --version
        rustc -vV
        echo "version ${GITHUB_REF#refs/heads/release/}"
    - name: document
      run: |
        cd doc && npm install && npm run docs:build
    - name: Upload web site
      uses: actions/upload-artifact@v4
      id: upload-generated-website
      with:
        name: website-output
        path: doc/.vitepress/dist
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: npm install -g pnpm
    - name: Build
      run: make web-demo
    - name: Upload generated web template
      uses: actions/upload-artifact@v4
      id: upload-generated-template
      with:
        name: template-output
        path: extension/webview/dist_web
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'sankooc/sankooc.github.io'
        ref: 'gh'
        token:  ${{ secrets.TEMPLATE_OUTPUT_REPO_TOKEN }}
    - name: Setup git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "sankooc@163.com"
    - name: clean
      run: |
        rm -rf .pcap
        rm -rf pcap
        rm -rf vs-shark
    - name: Download generated template
      uses: actions/download-artifact@v4
      with:
        name: template-output
        path: .pcap
    - name: Download generated website
      uses: actions/download-artifact@v4
      with:
        name: website-output
        path: vs-shark
    - name: Commit and push
      run: |
        mkdir pcap
        mv .pcap/* pcap
        cp tmp/* pcap
        rm -rf .pcap
        git add .
        git commit -m "auto release"
        git push